---
# Run pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: check-json
        exclude: ^tsconfig.json$
      - id: check-toml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: forbid-submodules
      - id: pretty-format-json
        exclude: ^tsconfig.json$
        args: [--autofix]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013, MD024, MD051, --, --ignore node_modules]
